# Using node 16.17.1
#
name: Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@0a29871fe2b0200a17a4497bae54fe5df0d973aa # v1.115.3
        with:
          ruby-version: '3.0.3' # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          cache-version: 0 # Increment this number if you need to re-download cached gems
        env:
          ImageOS: ubuntu20
      - uses: actions/setup-node@v2
        with:
          node-version: 16.17.1
      - run: yarn
      - name: Build
        run: |
          make install && make build
      # setup git commiter and deploy to gh-pages
      - name: Setup git commiter
        run: |
          git config --global user.name "Mandakara Sadewa"
          git config --global user.email "mdswa@zxce3.net"
      
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: _site
          git-config-email: mdswa@zxce3.net
          git-config-name: Mandakara Sadewa